#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=52

start() {
        if [ -e /proc/fppmode ]; then
	  if [ "`grep "0" /proc/fppmode`" ]; then
            exit 0
          fi
        fi
	insmod cdx
	echo done
}

stop(){
        if [ -e /proc/fppmode ]; then
	  if [ "`grep "0" /proc/fppmode`" ]; then
            exit 0
          fi
        fi
	rmmod cdx
	echo done
}
